baseURL = "/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 5
  showReadingTime = false
  rssFullText = true

[languages]
  [languages.en]
    title = "108 Minutes"
    copyright = "©2020 Sean Johnson"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"

    [languages.en.params.logo]
      logoText = "4 8 15 16 23 42"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
        weight = -10
      [[languages.en.menu.main]]
        identifier = "tags"
        name = "dharma"
        url = "/tags"
        weight = -9
      [[languages.en.menu.main]]
        identifier = "photos"
        name = "photos"
        url = "https://pics.108minutes.net/"
        weight = -8
      [[languages.en.menu.main]]
        identifier = "tech"
        name = "tech"
        url = "https://skj.dev"
        weight = -7
